version: '3.7'

#network bridge enable the services to talk to each other. One service might at some point send a request to the other.
#create it with $docker network create skynet
networks:
  skynet:
    external:
      name: skynet

services:
  webApplicationA:
    image: webapplicationa:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile_webApplicationA
    hostname: "webapplication-a"
    ports:
      - "8080:8080"
    networks:
      - skynet

  webApplicationB:
    image: webapplicationb:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile_webApplicationB
    hostname: "webapplication-b"
    ports:
      - "8081:8081"
    networks:
      - skynet
